service: SFTK-0001-SWAPI-SWP

custom:
  secrets: ${file(secrets.json)}
  prefix: ${self:service}
package:
  exclude:
    # - ./node_modules
    # - node_modules/**
    - nodejs
    - src/Database/config
    - secrets*.json
    - .env*

provider:
  name: aws
  stackName: ${self:custom.prefix}-${self:custom.secrets.SHORT_STAGE}
  runtime: nodejs18.x
  environment:
    DYNAMO_FILMS_TABLE: ${self:custom.secrets.DYNAMO_FILMS_TABLE}
    SWAPI_HOST: ${self:custom.secrets.SWAPI_HOST}
  iam:
    role:
      name: dynamo
      statements:
        - Effect: Allow
          Resource: '*'
          Action: 
            - dynamo:GetItem
            - dynamo:UpdateItem
  timeout: 30
  stage: ${self:custom.secrets.STAGE}

functions:
  getFilm:
    name: "${self:custom.prefix}-${self:custom.secrets.SHORT_STAGE}-LA-00-getFilm"
    events:
      - http:
          path: /{proxy+}
          method: any 
          cors: true
    # image: baseimage
    handler: dist/lambda.handler

resources:
  Resources:
    CharactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.prefix}${self:custom.secrets.SHORT_STAGE}-characters
    ColaboratorsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: document
            AttributeType: S
        KeySchema:
          - AttributeName: document
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.prefix}${self:custom.secrets.SHORT_STAGE}-colaborator
    

plugins:
  - serverless-offline
  - serverless-jetpack


          
  



      
