service: SFTK-0001-SWAPI-SWP

custom:
  prefix: ${self:service}
package:
  exclude:
    # - ./node_modules
    # - node_modules/**
    - nodejs
    - src/Database/config
    - secrets*.json
    - .env*
useDotenv: true 
provider:
  name: aws
  stackName: ${self:custom.prefix}-${env:SHORT_STAGE}
  runtime: nodejs18.x
  environment:
    DYNAMO_FILMS_TABLE: ${env:DYNAMO_FILMS_TABLE}
    SWAPI_HOST: ${env:SWAPI_HOST}
    COLABORATOR_TABLE: ${env:COLABORATOR_TABLE}
    DYNAMO_USER_TABLE: ${env:DYNAMO_USER_TABLE}
    REGION: ${env:REGION}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_USER_POOL_CLIENT: ${env:COGNITO_USER_POOL_CLIENT}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    EMAIL_HOST: ${env:EMAIL_HOST}
    EMAIL_PORT: ${env:EMAIL_PORT}
  iam:
    role:
      name: dynamo
      statements:
        - Effect: Allow
          Resource: '*'
          Action: 
            - dynamo:GetItem
            - dynamo:UpdateItem
  timeout: 30
  stage: dev

functions:
  getFilm:
    name: "${self:custom.prefix}-${env:SHORT_STAGE}-LA-00-getFilm"
    events:
      - http:
          path: /{proxy+}
          method: any 
          cors: true
    # image: baseimage
    handler: dist/lambda.handler

resources:
  Resources:
    CharactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.prefix}${env:SHORT_STAGE}-characters
    ColaboratorsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: document
            AttributeType: S
        KeySchema:
          - AttributeName: document
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.prefix}${env:SHORT_STAGE}-colaborator
    
plugins:
  - serverless-offline
  - serverless-jetpack
