name: test work flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2


      - name: test to print variables  
        run: echo Hello!!! from ${{github.workflow}} triggered by ${{github.actor}} with ${{github.event_name}} event
      
      - name: install dependencies
        run: npm install 

      - name: unit test
        run: npm run test
      
      - name: deployment
        run: npm run serverless deploy  

