name: test work flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2


      - name: test to print variables  
        run: echo Hello!!! from ${{github.workflow}} triggered by ${{github.actor}} with ${{github.event_name}} event 
      
      - name: install dependencies
        run: npm install 

      - name: unit test
        run: npm run test
      
      - name: deployment
        run: echo $SWAPI_HOST && npm run deploy
        env:
          COGNITO_USER_POOL_CLIENT: ${{ vars.COGNITO_USER_POOL_CLIENT }}
          COGNITO_USER_POOL_ID: ${{vars.COGNITO_USER_POOL_ID}}
          COLABORATOR_TABLE: ${{vars.COLABORATOR_TABLE}}
          DYNAMO_FILMS_TABLE: ${{vars.DYNAMO_FILMS_TABLE}}
          DYNAMO_USER_TABLE: ${{vars.DYNAMO_USER_TABLE}}
          EMAIL_HOST: ${{vars.EMAIL_HOST}}
          EMAIL_PORT: ${{vars.EMAIL_PORT}}
          REGION: ${{vars.REGION}}
          SHORT_STAGE: ${{vars.SHORT_STAGE}}
          STAGE: ${{vars.STAGE}}          
          SWAPI_HOST: ${{vars.SWAPI_HOST}}
          EMAIL_PASS: ${{vars.EMAIL_PASS}}
          EMAIL_USER: ${{vars.EMAIL_USER}}
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{vars.AWS_SECRET_ACCESS_KEY}}
          
