name:

on:[push]

jobs:
  build:

  runs-on: ubuntu-18

  steps:
    - uses: actions/checkout@v2

    - name: test to print variables  
      run: echo Hello!!! from ${{github.workflow}} triggered by ${{github.actor}} with ${{github.event_name}} event